<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-22QOM6E" failures="1" tests="4" name="Default test(failed)(failed)(failed)" time="0.062" errors="0" timestamp="2024-01-21T14:56:50 IST">
  <testcase classname="Practice.Retry_Analyser" name="sample" time="0.018">
    <skipped/>
  </testcase> <!-- sample -->
  <testcase classname="Practice.Retry_Analyser" name="sample" time="0.001">
    <skipped/>
  </testcase> <!-- sample -->
  <testcase classname="Practice.Retry_Analyser" name="sample" time="0.001">
    <skipped/>
  </testcase> <!-- sample -->
  <testcase classname="Practice.Retry_Analyser" name="sample" time="0.001">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at Practice.Retry_Analyser.sample(Retry_Analyser.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- sample -->
</testsuite> <!-- Default test(failed)(failed)(failed) -->
